# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
  burritos_listener:
    class: AppBundle\Listener\BurritoListener
    arguments: ["@slack.client"]
    tags:
      - name: kernel.event_listener
        event: slack.command.received
        method: handleMessageEvent

  gif_listener:
    class: AppBundle\Listener\GifShrinkingListener
    arguments: ["@slack.client", "@logger"]
    tags:
      - name: kernel.event_listener
        event: slack.command.received
        method: handleMessageEvent
